CREATE DATABASE IF NOT EXISTS HACKATHON_IOT;

CREATE SCHEMA IF NOT EXISTS HACKATHON_IOT.RAW;
CREATE SCHEMA IF NOT EXISTS HACKATHON_IOT.CLEAN;
CREATE SCHEMA IF NOT EXISTS HACKATHON_IOT.ANALYTICS;
USE DATABASE HACKATHON_IOT;

CREATE TABLE IF NOT EXISTS RAW.IOT_EVENTS (
    id INT,
    device_id STRING,
    latitude FLOAT,
    longitude FLOAT,
    event_timestamp STRING,
    op STRING,
    raw_payload VARIANT,
    loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
SELECT * FROM HACKATHON_IOT.RAW.IOT_EVENTS_bronze;
SELECT * FROM HACKATHON_IOT.RAW.IOT_EVENTS_Silver;
SELECT * FROM HACKATHON_IOT.RAW.IOT_EVENTS_Gold;
